exynos4: smdkv310/origen: Fix build break
The common spl_boot.c contains certain defines present only in Exynos5
and thus breaks compilation for Exynos4-based machines such as SMDKV310
and Origen. The build error is as follows:

spl_boot.c:99:12: error: ‘SPI_FLASH_UBOOT_POS’ undeclared (first use in
this function)
spl_boot.c:99:12: note: each undeclared identifier is reported only once
for each function it appears in
spl_boot.c:99:33: error: ‘CONFIG_BL2_SIZE’ undeclared (first use in this
function)

BUG=None
TEST=make smdkv310_config; make
     make origen_config; make
     make s5p_goni_config; make
     make s5pc210_universal; make
     make smdk5250_config; make
Change-Id: I94d8f6a94c04fc15d374dd4af220fa9adb518be8
Signed-off-by: Abhilash Kesavan <a.kesavan@samsung.com>
Reviewed-on: https://gerrit.chromium.org/gerrit/17805
Reviewed-by: Tom Wai-Hong Tam <waihong@chromium.org>
Reviewed-by: Simon Glass <sjg@chromium.org>