exynos3: smdkc100: Fix build break
SMDKC100 is Exynos3 based and doesnot need to have libexynos-common
which is for Exynos4 and Exynos5. Fixes the following build error:

arch/arm/cpu/armv7/s5pc1xx/reset.S:31:multiple definition of `reset_cpu'
arch/arm/cpu/armv7/exynos-common/libexynos-common.o:arch/arm/cpu/armv7/
exynos-common/soc.c:28:first defined here

BUG=None
TEST=make smdkc100_config; make
Change-Id: I144b4ddff1119e97ce4f5a8ac9c0acbe88ba6c92
Signed-off-by: Abhilash Kesavan <a.kesavan@samsung.com>
Reviewed-on: https://gerrit.chromium.org/gerrit/17804
Reviewed-by: Simon Glass <sjg@chromium.org>
Reviewed-by: Tom Wai-Hong Tam <waihong@chromium.org>