exynos: Remove board_get_revision() warning
Remove this warning by including the required header:

spl_boot.c: In function ‘board_init_f’:
spl_boot.c:159:2: warning: implicit declaration of function ‘board_get_revision’ [-Wimplicit-function-declaration]

BUG=chromium-os:31212
TEST=build and boot to kernel on daisy

Change-Id: Iff6c71dce591329a79c07c1a34f3c588c3f88142
Signed-off-by: Simon Glass <sjg@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/23353